### PR TITLE
Dependency Updates

### PR DESCRIPTION
**Pull request by jentfoo**
Updated using `go get -t -u=patch ./...`, then manually updated go net and crypto to address recent CVE's.

After merged I will submit another PR to merge `master` into the `teleport` branch.

### CODE REVIEW

**Comment by wadells** [comment]
Should we be keeping master fast-forwardable to the upstream, and set the default branch (and target of this PR) to `teleport`/`teleport.1`?  I'm not sure we get any meaningful security benefit by updating these on master, and it may make future syncs more difficult.

Adding @gabrielcorado and @smallinsky who have made recent contributions for their thoughts about how this fork should be maintained.

**Comment by jentfoo** [comment]
I actually was reconsidering my comment about merging into the `teleport` branch.

We should either merge `teleport` into `master` or we should update our default branch to be `teleport`.

I personally don't see any reason `master` needs to be fast forwadable to the fork, and would recommend we just continue to use `master` as our primary work branch.

Let me know your thoughts.

**Comment by wadells** [comment]
> I personally don't see any reason `master` needs to be fast forwadable to the fork, and 

Consistency with how we manage our other forks.  For example, see: https://gravitational.slab.com/posts/web-authn-and-passwordless-development-avzq9xn1#h0m6u-how-to-update-gravitational-go-libfido-2

> would recommend we just continue to use `master` as our primary work branch.

We're not using master as the primary work branch currently: See:

https://github.com/gravitational/teleport/blob/3c0707c7102122acbacd1cd219d35a206d576339/go.mod#L373
Which refrences https://github.com/gravitational/go-mssqldb/commit/0f00ae61fb60f7db4268cd73036452bb3d037b90
which comes from `teleport.1` and https://github.com/gravitational/go-mssqldb/pull/7

**Comment by jentfoo** [comment]
I feel like I have run across equal qty's of fork's where the master branch was where additional development occurred.  For example: https://github.com/gravitational/go-oidc

In any case, I don't have a strong preference besides it being important that the teleport / active branch is listed as the default branch.  This fork's master branch has already diverged because the default branch was not updated.

Personally I still prefer `master` being our active branch name as that remains consistent not just with forks but all of our repos.  I don't see why an unmodified upstream needs to be committed with our fork, but if we do want that, I suggest we use a branch like `upstream-master` so it's explicit.

I only discuss it in detail since this repo has already diverged, so we will need a merge and then force-push if we want to resume the prior pattern (as well as a commit to github-terraform to update the default branch).  Alternatively if we want to continue to use `master` we just need to merge the `teleport.1` branch into master.

**Comment by smallinsky** [comment]
@wadells @jentfoo This repo is quite problematic because formerly we have used the `https://github.com/denisenkom/go-mssqldb` but right now we have switched to https://github.com/microsoft/go-mssqldb. Since GH doesn't allow to fork twice we cannot create the fork  `microsoft/go-mssqldb.` so right now we are using `teleport.1` that point to `microsoft/go-mssqldb.` and updates are handled manually.

**Comment by jentfoo** [comment]
Thank you for the history @smallinsky, I did not realize that.

Do we want to delete and recreate this fork (obviously pushing our changes back following)?  If that's desired, I am happy to help, and it could avoid future confusion.

If we just want to just keep moving forward with this repo as is, I submitted this PR to change the default branch: https://github.com/gravitational/github-terraform/pull/452

I will close this PR either way, just leaving open until discussion has concluded.  Once settled I will submit another PR if necessary.

**Comment by jentfoo** [comment]
Default branch has been updated.  Closing this PR now, if needed I will open a new one against `teleport.1`.

@smallinsky If there is a desire to recreate this fork let me know and I will get a plan in place.  Thank you!

**Comment by smallinsky** [comment]
@jentfoo 
> Do we want to delete and recreate this fork (obviously pushing our changes back following)? If that's desired, I am happy to help, and it could avoid future confusion

In that that way we will break teleport binary build from old tags like v11.0.0 where we still need keep the told fork. 

Do you have any idea how to replace the fork without breaking legacy builds ?

**Comment by jentfoo** [comment]
@smallinsky If we recreate the fork, here was my plan in detail:
1) Rename this repo and archive it (temporary breakage of old legacy builds)
2) Create a new fork from microsoft
3) Push tags and branches from this (renamed) fork into the new fork.  I believe this should fix the legacy builds as long as they reference a tag
4) We still need to decide what the active working branch should be.  I suggest we move `teleport.1` into `master` of the new fork, but I don't feel too strongly.

Let me know what you think

**Comment by gabrielcorado** [comment]
I think if we can keep the git references (commits hashes), it won't break old versions. About the branch name, looking at other forks, it seems a go-to for having our changes located at a `teleport` branch and keeping the `master/main` synced with the fork, but this is just a name convention.

**Pull request closed without merging**
